[package]
name = "compute_stream"
version = "1.0.0"

[addresses]
computestream = "0x69fa4604bbf4e835e978b4d7ef1cfe365f589291428a9d6332b6cd9f4e5e8ff1"
std = "0x1"
aptos_std = "0x1"
aptos_framework = "0x1"

[dev-addresses]
computestream = "0x123"

[dependencies.AptosFramework]
git = "https://github.com/movementlabsxyz/aptos-core.git"
rev = "l1-migration"
subdir = "aptos-move/framework/aptos-framework"