[package]
name = "compute_stream"
version = "1.0.0"

[addresses]
computestream = "0xd6d9d27d944417f05fd2d2d84900ff379d0b7d7d00811bfe08ceedf0e64288b9"
std = "0x1"
aptos_std = "0x1"
aptos_framework = "0x1"

[dev-addresses]
computestream = "0x123"

[dependencies.AptosFramework]
git = "https://github.com/movementlabsxyz/aptos-core.git"
rev = "l1-migration"
subdir = "aptos-move/framework/aptos-framework"